version: '3'
services:
  mapillary-tools: 
    build: .
    container_name: mapillary-tools
    volumes:
      - ~/mapillary/photos:/photos
      - ~/mapillary/videos:/videos
      - ~/mapillary/gpx:/gpx
      - ~/mapillary/config/credentials:/root/.config/mapillary/configs/MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo1YTM0NjRkM2EyZGU5MzBh
